# This is a basic workflow to help you get started with Actions

name: CI CD APRIANA - Deploy website on push

on: 
 push:
    branches: 
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: {{SERVER.PROD_SERVER}}
        username: {{SERVER.PROD_USER}}
        password: {{SERVER.PROD_PASSWORD}}
        # local-dir: ./dist/
        # server-dir: ./apriana/
        # dangerous-clean-slate: true 